### ISSUE TITLE
Vaulty is not loading in the new expansion....

### ISSUE THREAD

**Issue by avrosati** [himea-saito/Vaulty#5]
The Lua error reports that you may have been using a deprecated call for loading a WoW interface/AddOn. 

Here is what the error text reads:

1x Vaulty/vaulty.lua:1: attempt to index global 'C_Addons' (a nil value)
[string "@Vaulty/vaulty.lua"]:1: in main chunk

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Addons' (a nil value)"

**Comment by himea-saito** [comment]
@avrosati Sorry for the delay here, I haven't played Retail in a while. I wasn't able to replicate the `C_Addons` error you're getting, but I was getting a very similar error for `LoadAddOn` which has been deprecated in the new expansion. I updated it to use C_AddOns which has fixed the error for me and I'm expecting it will resolve what you're seeing as well.

https://github.com/himea-saito/Vaulty/releases/tag/1.4-release
